#!/usr/bin/env bash
rm ~/.zshrc ~/.config/nvim/init.vim ~/.gitconfig ~/.gitignore_global ~/.tmux.conf ~/.inputrc
ln -s ~/dotfiles_mac/zshrc ~/.zshrc
ln -s ~/dotfiles_mac/nvimrc ~/.config/nvim/init.vim
ln -s ~/dotfiles_mac/gitconfig ~/.gitconfig
ln -s ~/dotfiles_mac/gitignore_global ~/.gitignore_global
ln -s ~/dotfiles_mac/tmux.conf ~/.tmux.conf
ln -s ~/dotfiles_mac/inputrc ~/.inputrc
exit

